import './polyfills.js';
import type { ADWebAuthConfig } from '@cityssm/ad-web-auth-connector/types.js';
import type { Configuration as AvantiConfig } from '@cityssm/avanti-api';
import type { config as MSSQLConfig } from 'mssql';
import type { ConfigActiveDirectory, ConfigEmployeeEligibilityFunction, ConfigEmployeeSortKeyFunction, ConfigTemporaryUserCredentials } from '../types/configTypes.js';
export declare function getConfigProperty(propertyName: 'application.applicationName'): string;
export declare function getConfigProperty(propertyName: 'application.backgroundURL'): string;
export declare function getConfigProperty(propertyName: 'application.bigLogoURL'): string;
export declare function getConfigProperty(propertyName: 'application.smallLogoURL'): string;
export declare function getConfigProperty(propertyName: 'application.httpPort'): number;
export declare function getConfigProperty(propertyName: 'application.userDomain'): string;
export declare function getConfigProperty(propertyName: 'application.allowTesting'): boolean;
export declare function getConfigProperty(propertyName: 'tempUsers'): ConfigTemporaryUserCredentials[];
export declare function getConfigProperty(propertyName: 'activeDirectory'): ConfigActiveDirectory | undefined;
export declare function getConfigProperty(propertyName: 'adWebAuthConfig'): ADWebAuthConfig | undefined;
export declare function getConfigProperty(propertyName: 'application.maximumProcesses'): number;
export declare function getConfigProperty(propertyName: 'reverseProxy.disableCompression'): boolean;
export declare function getConfigProperty(propertyName: 'reverseProxy.disableEtag'): boolean;
export declare function getConfigProperty(propertyName: 'reverseProxy.urlPrefix'): string;
export declare function getConfigProperty(propertyName: 'session.cookieName'): string;
export declare function getConfigProperty(propertyName: 'session.doKeepAlive'): boolean;
export declare function getConfigProperty(propertyName: 'session.maxAgeMillis'): number;
export declare function getConfigProperty(propertyName: 'session.secret'): string;
export declare function getConfigProperty(propertyName: 'features.attendance.absences'): boolean;
export declare function getConfigProperty(propertyName: 'features.attendance.callOuts'): boolean;
export declare function getConfigProperty(propertyName: 'features.attendance.returnsToWork'): boolean;
export declare function getConfigProperty(propertyName: 'features.attendance.afterHours'): boolean;
export declare function getConfigProperty(propertyName: 'features.employees.avantiSync'): boolean;
export declare function getConfigProperty(propertyName: 'features.selfService'): boolean;
export declare function getConfigProperty(propertyName: 'mssql'): MSSQLConfig;
export declare function getConfigProperty(propertyName: 'settings.avantiSync.config'): AvantiConfig;
export declare function getConfigProperty(propertyName: 'settings.avantiSync.locationCodes'): string[];
export declare function getConfigProperty(propertyName: 'settings.printPdf.contentDisposition'): 'attachment' | 'inline';
export declare function getConfigProperty(propertyName: 'settings.employeeEligibilityFunctions'): ConfigEmployeeEligibilityFunction[];
export declare function getConfigProperty(propertyName: 'settings.employeeSortKeyFunctions'): ConfigEmployeeSortKeyFunction[];
export declare function getConfigProperty(propertyName: 'settings.employeeNumberRegularExpression'): RegExp | undefined;
export declare function getConfigProperty(propertyName: 'settings.recentDays'): number;
export declare function getConfigProperty(propertyName: 'settings.updateDays'): number;
export declare function getConfigProperty(propertyName: 'settings.selfService.path'): `/${string}`;
export declare function includeAttendance(): boolean;
export declare const historicalDays: number;
export declare const deleteDays: number;
export declare const keepAliveMillis: number;
declare const _default: {
    getConfigProperty: typeof getConfigProperty;
    includeAttendance: typeof includeAttendance;
    historicalDays: number;
    deleteDays: number;
    keepAliveMillis: number;
};
export default _default;
