import './polyfills.js';
import type { ADWebAuthConfig } from '@cityssm/ad-web-auth-connector/types.js';
import type { Configuration as AvantiConfig } from '@cityssm/avanti-api';
import type { config as MSSQLConfig } from 'mssql';
import type { ConfigActiveDirectory, ConfigEmployeeEligibilityFunction, ConfigEmployeeSortKeyFunction, ConfigTemporaryUserCredentials } from '../types/configTypes.js';
export declare function getConfigProperty(propertyName: 'application.applicationName' | 'application.backgroundURL' | 'application.bigLogoURL' | 'application.smallLogoURL' | 'application.userDomain' | 'reverseProxy.urlPrefix' | 'session.cookieName' | 'session.secret'): string;
export declare function getConfigProperty(propertyName: 'application.httpPort' | 'application.maximumProcesses' | 'session.maxAgeMillis' | 'settings.recentDays' | 'settings.updateDays'): number;
export declare function getConfigProperty(propertyName: 'application.allowTesting' | 'reverseProxy.disableCompression' | 'reverseProxy.disableEtag' | 'session.doKeepAlive' | 'features.attendance.absences' | 'features.attendance.callOuts' | 'features.attendance.returnsToWork' | 'features.attendance.afterHours' | 'features.employees.avantiSync' | 'features.selfService'): boolean;
export declare function getConfigProperty(propertyName: 'tempUsers'): ConfigTemporaryUserCredentials[];
export declare function getConfigProperty(propertyName: 'activeDirectory'): ConfigActiveDirectory | undefined;
export declare function getConfigProperty(propertyName: 'adWebAuthConfig'): ADWebAuthConfig | undefined;
export declare function getConfigProperty(propertyName: 'mssql'): MSSQLConfig;
export declare function getConfigProperty(propertyName: 'settings.avantiSync.config'): AvantiConfig;
export declare function getConfigProperty(propertyName: 'settings.avantiSync.locationCodes'): string[];
export declare function getConfigProperty(propertyName: 'settings.printPdf.contentDisposition'): 'attachment' | 'inline';
export declare function getConfigProperty(propertyName: 'settings.employeeEligibilityFunctions'): ConfigEmployeeEligibilityFunction[];
export declare function getConfigProperty(propertyName: 'settings.employeeSortKeyFunctions'): ConfigEmployeeSortKeyFunction[];
export declare function getConfigProperty(propertyName: 'settings.employeeNumberRegularExpression'): RegExp | undefined;
export declare function getConfigProperty(propertyName: 'settings.selfService.path'): `/${string}`;
export declare function includeAttendance(): boolean;
export declare const historicalDays: number;
export declare const deleteDays: number;
export declare const keepAliveMillis: number;
declare const _default: {
    getConfigProperty: typeof getConfigProperty;
    includeAttendance: typeof includeAttendance;
    historicalDays: number;
    deleteDays: number;
    keepAliveMillis: number;
};
export default _default;
